### ISSUE TITLE
Google Translate Function Is Unhappy

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#147] opened 2009-11-17 15:53 UTC
Haven't been using Anki much lately, but come into once or twice a week to do reps. Without having changed anything in anki or pytk got an interesting new error I can't scare away. Possibly changes to google transalte?

An error occurred in a plugin. Please contact the plugin author.
Please do not file a bug report with Anki.

Traceback (most recent call last):
  File "ankiqt\ui\facteditor.pyc", line 401, in 
  File "ankiqt\ui\facteditor.pyc", line 496, in onFocusLost
  File "anki\facts.pyc", line 125, in focusLost
  File "anki\hooks.pyc", line 26, in runHook
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\anki\hooks.py", line 97, in onFocusLost
    # Note: Ctrl-F9 is the HTML editor. Don't do this as it causes a conflict
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\anki\hooks.py", line 116, in updatefact
    self.action = QtGui.QAction("Pinyin Toolkit", self.mw)
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\utils.py", line 34, in suppressexceptions
    action()
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\anki\hooks.py", line 116, in 
    self.action = QtGui.QAction("Pinyin Toolkit", self.mw)
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\updater.py", line 65, in updatefact
    return output
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\updater.py", line 43, in updatefact
    for outputfile in output:
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\updatergraph.py", line 96, in reformatfield
    if all([(it in graph) and (graph[it][1]() is not None) for it in [reformatwhat] + reformatusings]) and (alwaysreformat or shouldreformat()):
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\utils.py", line 189, in **call**

  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\updatergraph.py", line 312, in fillme
    result = fillerfunction()
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\updatergraph.py", line 297, in 
    cannowfill[updatewhat].append((lambda inputs=inputs, updatefunction=updatefunction: updatefunction(*(inputs())),
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\updatergraph.py", line 147, in expression2simptrad
    meanings = dictionaryonline.gTrans(expression, glangcode, False)
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\dictionaryonline.py", line 40, in gTrans
    log.exception("Error while parsing Google response: %s" % repr(literal))
NameError: global name 'literal' is not defined
Traceback (most recent call last):
  File "ankiqt\ui\facteditor.pyc", line 401, in 
  File "ankiqt\ui\facteditor.pyc", line 496, in onFocusLost
  File "anki\facts.pyc", line 125, in focusLost
  File "anki\hooks.pyc", line 26, in runHook
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\anki\hooks.py", line 97, in onFocusLost
    # Note: Ctrl-F9 is the HTML editor. Don't do this as it causes a conflict
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\anki\hooks.py", line 116, in updatefact
    self.action = QtGui.QAction("Pinyin Toolkit", self.mw)
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\utils.py", line 34, in suppressexceptions
    action()
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\anki\hooks.py", line 116, in 
    self.action = QtGui.QAction("Pinyin Toolkit", self.mw)
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\updater.py", line 65, in updatefact
    return output
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\updater.py", line 43, in updatefact
    for outputfile in output:
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\updatergraph.py", line 96, in reformatfield
    if all([(it in graph) and (graph[it][1]() is not None) for it in [reformatwhat] + reformatusings]) and (alwaysreformat or shouldreformat()):
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\utils.py", line 189, in **call**

  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\updatergraph.py", line 312, in fillme
    result = fillerfunction()
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\updatergraph.py", line 297, in 
    cannowfill[updatewhat].append((lambda inputs=inputs, updatefunction=updatefunction: updatefunction(*(inputs())),
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\updatergraph.py", line 147, in expression2simptrad
    meanings = dictionaryonline.gTrans(expression, glangcode, False)
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\dictionaryonline.py", line 40, in gTrans
    log.exception("Error while parsing Google response: %s" % repr(literal))
NameError: global name 'literal' is not defined

**Comment by batterseapower** [comment] 2009-11-20 00:20
I've pushed a release (0.6.1) that fixes this urgent issue.

The problem was caused by Google updating their servers as you suspected.

The version on Github is only fixed on the v0.6-fixes branch. The master branch is still in a bit of a state of flux until I find time to finish off what I was doing there... (IIRC)

**Closed as completed by batterseapower** 2009-11-20 00:20 UTC

**Comment by Nick3C** [comment] 2009-11-22 11:34
Another good job max.

Quick note: a friend of mine had errors after upgrading. the toolkit kept saying there was no module called logger (when the .py and .pyc were both there). The solution was to delete and reinstall the toolkit (simple reinstall failed to resolve). Not really a serious problem, but rather peculiar.

**Comment by Nick3C** [comment] 2009-11-22 11:37
Incidentally, is there any way we can make pinyin toolkit errors fail gracefully? (i..e fail but allow the core functionality of the toolkit to keep working?)

For example, our previous problems with mapilib graphing causing the main toolkit to fail were far from idea. Likewise google translate is an ancillary feature. If one feature fails it would be much better to have the others still work.
