### ISSUE TITLE
audio problems on ubuntu (anki 0.9.9.8.4, py tookit 0.05)

### ISSUE THREAD

**Issue by poikiloid** [batterseapower/pinyin-toolkit#135] opened 2009-07-15 16:17 UTC
First, many thanks for the fantastic plugin!

I am using the unaltered (NOT modified using audacity) Windows version ChinesePod audio files  on my ubuntu 9.04 pc. There seem to be 2 different problems.
#1: The audio file of the last character is not fully played: it gets clipped. I have located the version of the file with hash filename that was automatically placed in the deck's media folder. It appears that the audio file is actually not the problem (i mean, the whole pronunciation is indeed contained in it)...Clipping seems to depend on the media player, because I tried with different players. It IS clipped by Totem (using Xine background) and mplayer (which is what anki uses, i belive); it is NOT clipped by RhythmBox nor VLC. I'm not sure, then if the problem lies more with anki/tookit or with mplayer. but in either case, any suggestions, like how to tweak mplayer to make it stop that?
#2: Also, on the second card shown after the deck is opened, the final character is played TWICE (and is still clipped). On the third card shown, the final character is pronouned THRICE (clipped). On the 4th, 4 times; and so on. I'm not sure how mplayer could be responsible, but who knows?

Note: I use this same deck occasionally on a mac OS 10.5, and have no problem. (I copy over the deck and media folder--i use local installs on both computers, not the portable version of anki).

**Comment by batterseapower** [comment] 2009-07-16 19:45
Those are crazy problems. I would have said its an Anki bug - do you have the same issue with audio inserted by things other than the toolkit?

**Comment by batterseapower** [comment] 2009-09-19 01:27
I haven't seen any other report of this, so I'm closing it as cannot reproduce. I don't think its a Toolkit problem in any event.

**Closed as completed by batterseapower** 2009-09-19 01:27 UTC
Labels: bug, cannot-reproduce
