### ISSUE TITLE
Unicode Bug

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#167] opened 2010-02-27 14:57 UTC
Here's the long runnning bug which 've been ignoring.., in this case, on the character: 零 (and the english field was not filled but others were)

An error occurred. Please:
Restart Anki. 
Tools > Advanced > Full Database Check. 
If it does not fix the problem, please copy the following
into a bug report:

C:\Program Files\Anki\lib\shared.zip\sqlalchemy\engine\default.py:230: SAWarning: Unicode type received non-unicode bind param value ''

**Comment by batterseapower** [comment] 2010-03-06 18:53
Hmm. I can't reproduce this on either Windows or OS X with the most recent code. Can you perhaps send me your Pinyin Toolkit.log from a session where you try to create such a card?

**Comment by Nick3C** [comment] 2010-03-07 04:13
Sent a log as requested.

**Comment by batterseapower** [comment] 2010-03-07 19:08
OK, I couldn't figure it out from the log, but I've added some code which may fix the bug. Can you try with the latest version from github?

**Comment by Nick3C** [comment] 2010-03-15 14:30
haven't seen the unicode error since you made this change but have hardly been using Anki. I will keep an eye out and let you know if I see it. On the other hand there are some new bugs (see other thread :) )

**Comment by batterseapower** [comment] 2010-03-25 13:50
Tentatively closing this as fixed

**Closed as completed by batterseapower** 2010-03-25 13:50 UTC
Labels: bug

**Comment by Nick3C** [comment] 2010-04-05 02:42
yes, I think so.
